### ISSUE TITLE
Zoom support / multires tiling

### ISSUE THREAD

**Issue by strarsis** [lukemnet/tridi#269]
It would be great if this viewer also supports zooming and multiresolution tiling/srcset, 
similar to what panorama viewers (that view from the opposite direction, inside-out) use for efficient zooming.

**Comment by lwojcik** [comment]
Thanks for the suggestion!

I looked at this and I agree zooming / multiple srcsets would be nice to have. However I'm currently unable to to implement this within a reasonable timeframe. It introduces additional complexity I may struggle to reliably maintain long-term within my current time resources.
