### ISSUE TITLE
Can this have momentum? i.e. when you let go it should keep going, based on how hard you spin it.

### ISSUE THREAD

**Issue by richbradshaw** [lukemnet/tridi#54]

**Comment by lwojcik** [comment]
Good suggestion. I'll see what can be done.

**Comment by lwojcik** [comment]
I dug a bit into the topic and I'm sad to inform I'm not implementing momentum directly in the project. None of my attempts at making it work felt good enough. Developing an optimal solution is a bit beyond my time budget. I don't want to tie it to any specific third party tool or library either.

I managed to get momentum working with [Impetus.js](https://chrisbateman.github.io/impetus/). Tridi methods for rotating image (`next()` / `prev()`) can be attached to `update` callback in a following fashion:

```javascript

var myTridi = new myTridi(/* options */);

myTridi.load();

new Impetus({
  source: document.querySelector('.tridi-element-here'),
  update: function(x, y) {
      // check x value and execute myTridi.next() or myTridi.prev() accordingly
  }
});
```

I'm open to making this kind of integrations as easy as possible. If there's anything specific I can do in my department that would make Tridi work better with any specific tool I'll be happy to consider it.
