### ISSUE TITLE
Pass object rather than ID

### ISSUE THREAD

**Issue by ap-prog** [lukemnet/tridi#57]
It would be nice to be able to pass an element object as well as an element ID. So, for example, Instead of only

new Tridi({
    element: '#car',
    images: imgArray
  }).load();

it would also be accept

const car = document.querySelector('#car');

new Tridi({
    element: car,
    images: imgArray
  }).load();

**Comment by lwojcik** [comment]
Thanks for the suggestion! I'll be adding this soon. It should land in a future release in first half of May.

**Comment by lwojcik** [comment]
Added support for custom HTML elements in v1.1.0. You can pass either a string with ID / class or HTMLElement (e.g. `document.querySelector('#something')`).

Let me know if you have any further questions / suggestions.
