### ISSUE TITLE
Onload event

### ISSUE THREAD

**Issue by ap-prog** [lukemnet/tridi#58]
It would be nice if it fired an onload event when it had at least loaded the initial image. I'm trying to position a "hidden" visualisation dynamically but I need to know when it's loaded to position other elements and to then display it.

**Comment by lwojcik** [comment]
Thanks for the suggestion! I'll be adding this soon. It should land in a future release in first half of May.

**Comment by lwojcik** [comment]
Added custom events in v1.1.0.

* https://tridi.lukem.net/examples/events.html
* https://tridi.lukem.net/notes/api.html#events

Once finished loading Tridi executes 'onLoad' event. I also added events to majority of significant lifecycle moments.

Let me know if you have further questions / suggestions.

**Comment by ap-prog** [comment]
Thanks for adding all the events.

One thing I'm having trouble with is working out which event gets triggered when the first image of a visualisation is displayed. I tried onViewerImageGenerate but when it gets triggered and I query the image size I get 12x12 (when the image is 480x360). What is it that I'm missing?

**Comment by lwojcik** [comment]
`onViewerImageGenerate` is the one that should the trick. `onLoad` might be another bet.

I'll check what's up and get back to you.

**Comment by lwojcik** [comment]
I made some internal tweaks and ensured `onViewerImageGenerate` fires only when image is fully loaded. Check out v1.1.2 and let me know if that works for you.

**Comment by ap-prog** [comment]
It's getting better but if I do something like

elem.update({
  location: "path/images/car/',
  format:"jpg",
  count: 36,
}, true);

onViewerImageGenerate is not triggered. I would expect that whenever a visualisation is updated with a change in the location of the images then onViewerImageGenerate would be reset and trigger again.

**Comment by ap-prog** [comment]
As a workaround in your stashImage method I added 
```
    var n = new Image;
    if (!i) n.addEventListener('load', visualisationLoaded); // <-- this line
    n.src = e,
```
and it seems to do what I need.

**Comment by lwojcik** [comment]
Good point. My intention for `onViewerImageGenerate` was to trigger it only on first load. I may not have   stated it clearly in the docs but I clearly want it to keep this that way.

In v1.2.0 I added `onViewerImageUpdate` which works in a similar fashion to `onViewerImageGenerate` but it triggers only when viewer is updated with new options object.

Thoughts?

**Comment by ap-prog** [comment]
Ok, so I would need to track onViewerImageGenerate the first time a visualisation is created and then onViewerImageUpdate every time after that. To me when the first image of a visualisation has been displayed is the same whether the visualisation has just been created or has just been updated.

BTW thanks for creating Tridi.

**Comment by lwojcik** [comment]
Thank YOU for using it and taking time to raise the issue! In case of further questions or requests let me know.
