### ISSUE TITLE
Update not clearing previous image

### ISSUE THREAD

**Issue by ap-prog** [lukemnet/tridi#64]
If I do an update to a different format of numbered images and there are less images that the previously displayed tridi then, once the tridi is dragged, the last image of the current tridi and the last image of previous tridi will both be displayed together. Tthe tridi will then not respond to user input.

**Comment by lwojcik** [comment]
Thanks for reporting! Will fix soon.

**Comment by lwojcik** [comment]
@ap-prog I commited a fix that should fix the problem. Could you let me know if [this version](https://raw.githubusercontent.com/lukemnet/tridi/ecce598e16e3ca3b297a46cb9ac38d63a8c6c198/dist/js/tridi.min.js) works in your case?

**Comment by lwojcik** [comment]
Fix released in v1.0.1.

**Comment by ap-prog** [comment]
Thanks, that seems to have fixed it.
